export const ui = {
  estado: document.querySelector("#estado"),
  inicio: document.querySelector("#inicio"),
  inicioTexto: document.querySelector("#inicioTexto"),
  modoTestSwitch: document.querySelector("#modoTestSwitch"),
  soloNoVistasSwitch: document.querySelector("#soloNoVistasSwitch"),
  rangeStart: document.querySelector('#rangeStart'),
  rangeEnd: document.querySelector('#rangeEnd'),
  aplicarRangoBtn: document.querySelector('#aplicarRangoBtn'),
  limpiarRangoBtn: document.querySelector('#limpiarRangoBtn'),
  iniciarBtn: document.querySelector("#iniciarBtn"),
  quiz: document.querySelector("#quiz"),
  resultado: document.querySelector("#resultado"),
  pregunta: document.querySelector("#pregunta"),
  preguntaAccion: document.querySelector("#preguntaAccion"),
  opciones: document.querySelector("#opciones"),
  siguienteBtn: document.querySelector("#siguienteBtn"),
  puntuacion: document.querySelector("#puntuacion"),
  resumen: document.querySelector("#resumen"),
  resumenBotones: document.querySelector("#resumenBotones"),
  repasarFallosBtn: document.querySelector("#repasarFallosBtn"),
  porcentajeVistas: document.querySelector("#porcentajeVistas"),
};
